---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: panoviewer
      namespace: panoviewer
      annotations:
          kubernetes.io/ingress.class: nginx
          certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    spec:
      tls:
        - hosts:
          - 685fernleaf.sethitow.com
          secretName: letsencrypt-prod
      rules:
        - host: api.soarcast.sethitow.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: soarcast-backend
                  servicePort: http